server:
  port: 8087
spring:
  application:
    name: auth-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
lware:
  jwt:
    secret: lware@Login(Auth}*^31)&lwg% # 登录校验的密钥
    pubKeyPath: F:\rsa\rsa.pub # 公钥地址
    priKeyPath: F:\rsa\rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: LW_TOKEN