server:
  port: 8081

spring:
  application:
    name: item-service
    #数据库
  datasource:
    url: jdbc:mysql://39.96.48.41:3306/shops?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 109837
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  rabbitmq:
    host: 39.96.48.41
    username: lwg
    password: 109837
    virtual-host: /lware
    template:
      exchange: lware.item.exchange
    #生产者确认机制,确保信息会正确发送,如果发送失败会有错误回执,从而触发重试
    publisher-confirms: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 5  #5秒钟发送一次心跳 表明服务活着
    lease-expiration-duration-in-seconds: 10 #10秒不发送就过期

mybatis:
  type-aliases-package: com.lwg.item.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl