server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 39.96.48.41
    port: 6379
    password: 109837
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/    #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

lware:
  jwt:
    pubKeyPath: F:\rsa\rsa.pub # 公钥地址
    cookieName: LW_TOKEN
