server:
  port: 8084
spring:
  application:
    name: goods-web
  thymeleaf:
    cache: false

  rabbitmq:
    host: 39.96.48.41
    username: lwg
    password: 109837
    virtual-host: /lware
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期