server:
  port: 8082

spring:
  application:
    name: shop-upload
  servlet:
    multipart:
      max-file-size: 10MB

eureka:
  client:
    registry-fetch-interval-seconds: 5  #间隔5秒拉取网关服务信息
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

fdfs:
  connect-timeout: 601  #连接超时时间
  so-timeout: 1501   #超时时间
  thumb-image:    #缩略图
    height: 60
    width: 60
  tracker-list:  #tracker地址
    - 192.168.136.128:22122
