server:
  port: 10010
spring:
  application:
    name: shop-gateway

eureka:
  client:
    registry-fetch-interval-seconds: 5  #间隔5秒拉取网关服务信息
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka
zuul:
  prefix: /api # 路由路径前缀
  routes:
    item-service: /item/** # 路由到商品的微服务
    search-service: /search/** # 路由到搜索微服务