server:
  port: 10010
spring:
  application:
    name: shop-gateway

eureka:
  client:
    registry-fetch-interval-seconds: 5  #间隔5秒拉取网关服务信息
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka
zuul:
  prefix: /api # 路由路径前缀
  routes:
    item-service: /item/** # 路由到商品的微服务
    search-service: /search/** # 路由到搜索微服务
    user-service: /user/**    #用户微服务
    auth-service: /auth/**    #授权中心微服务
  add-host-header: true    #携带nginx请求转发过来的域名head头信息
  sensitive-headers:      #配置禁止使用的头信息,这里设置为Null,否则set-cookie无效

ribbon:
  connectionTimeout: 1000  #获取连接超时时间
  readTimeout: 100   #通讯超时时间