server:
  port: 8083
spring:
  application:
    name: search-service
  jackson:
    default-property-inclusion: non_null  # 配置json处理时忽略空值
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.136.130:9300
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    registry-fetch-interval-seconds: 5  #间隔5秒拉取网关服务信息
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
ribbon:
  ConnectTimeout: 10000 # ribbon链接超时时长
  ReadTimeout: 10000 # ribbon读取超时时间长